{% set name = "MEDM" %}
{% set version = "3_1_18" %}

package:
  name: ligo-{{ name|lower }}
  version: {{ version|replace('_','.') }}

source:
  url: https://github.com/epics-extensions/medm/archive/MEDM{{ version }}.tar.gz
  sha256: 78db1f81cee546501cce2298e3342e03007e00baa43b880a7a66ca4a3d181ee3

  patches:
    - 0000-medm3_1_7_long_string.patch
    - 0001-medm3_1_7_macrofile.patch
    - 0002-medm3_1_9_macro2048.patch
    - 0003-remote_adl-2015-01-05.patch
    - 0004-remote-adl-2015-06-26.patch
    - 0005-version-update-2015-06-29.patch
    - 0006-enable-sciplot.patch
    - 0007-timemachine.patch
    - 0008-reorder-the-context-menu.patch
    - 0009-fix-empty-values-in-argstrings.patch
    # don't statically compile to libraries from macports macOS
    # - no-macports.patch  # [osx]

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - epics-base
    - epics-extensions
    - openmotif-dev
    - xorg-libx11  # [unix]
    - xorg-libxext  # [unix]
    - xorg-libxmu  # [unix]
    - xorg-libxp  # [unix]
    - xorg-libxt  # [unix]
  run:
    - epics-base
    - openmotif
    - xorg-libx11  # [unix]
    - xorg-libxext  # [unix]
    - xorg-libxmu  # [unix]
    - xorg-libxp  # [unix]
    - xorg-libxt  # [unix]
  run_constrained:
    # this package conflicts with epics-medm
    - epics-medm >9999

test:
  commands:
    - medm -h

about:
  home: https://epics.anl.gov/extensions/medm/
  dev_url: https://github.com/epics-extensions/medm/
  doc_url: https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html
  license: EPICS
  license_file: LICENSE
  summary: Motif Editor and Display Manager
  description: |
    MEDM is a graphical user interface tool for designing and implementing control
    screens for EPICS-based control systems. Displays contain graphical objects that
    can display and/or change the values of EPICS process variables using the
    Channel Access network protocol. Supported graphical objects include buttons,
    meters, sliders, text displays/entries, and graphs.

    MEDM has two modes of operation, EDIT and EXECUTE. Displays are created and
    edited in EDIT mode, and run in EXECUTE mode.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - pthomasj
    - evonreis
